### PR TITLE
Added bower config

### PR DESCRIPTION
**Pull request by cristinecula**
Hello Federico,

This change will allow publishing the library to the bower repository.

### CODE REVIEW

**Comment by federico-lox** [comment]
Thanks for the contribution :+1:

**Comment by cristinecula** [comment]
Hey, thanks for merging this!

I registered the library on bower as **pubsub.js** and now anyone can use your awesome work!



You should add a valid _semver tag_ so bower does not complain. I suggest tagging the latest commit as **0.1.0** so it matches the bower.json file.

Cheers,
cristi@blogvio.com

**Comment by federico-lox** [comment]
Sure, here we go:

https://github.com/federico-lox/pubsub.js/tree/0.1.0

Semver 2.0.0 compliant :bow:

**Comment by cristinecula** [comment]
Awesome!

Thanks a lot. I can update my bower dependencies now.

**Pull request merged**
